### ISSUE TITLE
CocosCreatorInspector咋不更新了

### ISSUE THREAD

**Issue by GAMEKON** [tidys/CocosCreatorPlugins#12]
呢？

**Comment by tidys** [comment]
作者开发了更佳友好的插件来替代这个web版本的Inspector插件
欢迎下载使用:
http://store.cocos.com/stuff/show/178982.html

**Comment by tidys** [comment]
我解释下为什么不再维护chrome插件版本的inspector
1. chrome插件上架Google商店，需要25美金的开账户费用
2. 国内是无法访问chrome插件商店的，也就造成了即使我上传了，大部分还需要翻墙才能下载
3. 不通过chrome插件商店下载的话，需要解压安装，而这个安装教程，也给不少新手造成了困惑
4. chrome只能在chrome内核的浏览器中使用，也就是只能调试web环境，我更希望inspector能全平台通吃

上述4个原因，我感觉维护chrome插件版本，不是太划算，于是，插件版本的inspector也就诞生了，插件版本的inspector实现了全平台调试，从长远来看，更符合我个人的维护远景

所以，chrome版本的inspector我就完全开源了，如果有可能，会更新，这个随心情了
