### ISSUE TITLE
请不要在数组的字段后加 s

### ISSUE THREAD

**Issue by jinceon** [tidys/CocosCreatorPlugins#17]
![image](https://user-images.githubusercontent.com/1641265/54995536-e80f0a80-5001-11e9-8ab7-15010113f5b5.png)
比如我的excel有3列，hero_1, hero_2, hero_3
导出成json后，列名`hero_1`会删除下划线后的内容，并加上 `s` 变成 heros
问题是：hero的复数是 heroes

这就有点蛋疼了，不管3721就加一个 s 。
要知道复数形式不仅仅是加s呀，
可能是 加es，可能是变y为i再加es，可能是man->men, chile->children等等

建议不要修改字段名，保留原样。就去掉_下划线后的内容就好

**Comment by jianguila** [comment]
agree no more

**Comment by jinceon** [comment]
不好意思，我用的是同事改过的插件。。

**Comment by tidys** [comment]
这就尴尬了,一脸懵逼的锅甩了过来

**Comment by jinceon** [comment]
> 这就尴尬了,一脸懵逼的锅甩了过来

对不起哈，同事在你的工具上改的，也不换个名字，哈哈哈
我发现后想删掉，发现我删不了。就close了
