### ISSUE TITLE
我这边用了资源压缩插件 但是编辑器提示Error: Cannot find module 'D:\Cocos\pro\CocosCreator\NewProject\packages\res-compress\node_modules\lamejs' 请问怎么解决？

### ISSUE THREAD

**Issue by zxa308078684** [tidys/CocosCreatorPlugins#22]

**Comment by tidys** [comment]
项目下载下来之后,需要npm install安装一下依赖

**Comment by zxa308078684** [comment]
谢谢




------------------ 原始邮件 ------------------
发件人: "tidy"<notifications@github.com>; 
发送时间: 2019年7月13日(星期六) 下午4:13
收件人: "tidys/CocosCreatorPlugins"<CocosCreatorPlugins@noreply.github.com>; 
抄送: "断随."<308078684@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [tidys/CocosCreatorPlugins] 我这边用了资源压缩插件 但是编辑器提示Error: Cannot find module 'D:\Cocos\pro\CocosCreator\NewProject\packages\res-compress\node_modules\lamejs' 请问怎么解决？ (#22)




项目下载下来之后,需要npm install安装一下依赖
